version: '3.4'

services:
  refactordb:
    image: mcr.microsoft.com/mssql/server:2019-latest   
    ports:
     - "1433:1433"
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=L0calpaS5      
    networks:
      - refactor-network
      
  refactorlog:
    image: datalust/seq:latest
    ports:
      - "85:85"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - refactor-network

  refactorapi:
    image: refactor-this.api:${TAG:-latest}
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: src/Dockerfile
    networks:
      - refactor-network    
    depends_on:
      - refactordb
      - refactorlog

networks:
  refactor-network: